server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway    #eureka服务application名字

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com  #修改eureka服务status名字
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept  #忽略某个eureka服务
  prefix: /test #访问前缀
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept #替换eureka服务
    mydept.path: /mydept/** #访问实列

info:
  app.name: atguigu-microcloud
  company.name: www.gulin.vip
  build.artifactId: $project.artifactId$
  build.version: $project.version$

